import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'scripts/**/.build',
      // Vendored build artifacts: docs/html/assets/odyssey.iife.js is an
      // esbuild bundle of src/ui, regenerated by the command in CLAUDE.md.
      // Lint the source in src/ui, not the generated bundle.
      'docs/html/assets/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node scripts (example server, tooling) run on the Node runtime.
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly' },
    },
  },
);
