/**
 * Generate the Odyssey icon data modules from the design system's SVG set.
 *
 * Reads `<odyssey>/public/svgs/*.svg` and splits them into two libraries:
 *   - THEMEABLE — icons that inherit `currentColor` (recolour via CSS)
 *   - BRAND     — icons with baked-in colours / gradients (logos, status art)
 *
 * Emits `src/ui/icons-data.ts` and `src/ui/brand-icons-data.ts` (committed).
 * This is a maintainer tool; run it when the Odyssey icon set changes:
 *
 *   node scripts/generate-icons.mjs [path-to-odyssey/public/svgs]
 *
 * Default source path assumes a sibling `sunflower` checkout.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const SRC =
  process.argv[2] ??
  resolve(process.cwd(), '../sunflower/client-support/ui/ember-odyssey/public/svgs');
const OUT_DIR = resolve(process.cwd(), 'src/ui');

/** Extract `viewBox` (or synthesize from width/height) and the inner markup. */
function parse(svg) {
  const viewBox =
    svg.match(/viewBox="([^"]+)"/)?.[1] ??
    (() => {
      const w = svg.match(/\bwidth="(\d+)/)?.[1] ?? '24';
      const h = svg.match(/\bheight="(\d+)/)?.[1] ?? '24';
      return `0 0 ${w} ${h}`;
    })();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/i, '')
    .replace(/<\/svg>\s*$/i, '')
    .replace(/>\s+</g, '><')
    .trim();
  return { viewBox, body };
}

/**
 * True when the markup bakes in a colour → brand icon. A colour is a gradient,
 * or any `fill`/`stroke` (or inline `style` fill/stroke) value that isn't
 * `none`/`currentColor`/`inherit`/`transparent`. `clip-path`/`mask` `url(#…)`
 * references are NOT colours, so they don't count.
 */
function isBrand(body) {
  if (/<(?:linear|radial)Gradient|stop-color|fill:\s*#|stroke:\s*#/i.test(body)) return true;
  const colours = body.match(/(?:fill|stroke)="([^"]*)"/gi) ?? [];
  return colours.some((attr) => {
    const value = attr.split('"')[1].toLowerCase().trim();
    return !['', 'none', 'currentcolor', 'inherit', 'transparent'].includes(value);
  });
}

const themeable = {};
const brand = {};
for (const file of readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort()) {
  const name = file.replace(/\.svg$/, '');
  const { viewBox, body } = parse(readFileSync(join(SRC, file), 'utf8'));
  if (!body) continue;
  (isBrand(body) ? brand : themeable)[name] = { viewBox, body };
}

const header = (name) =>
  `// AUTO-GENERATED by scripts/generate-icons.mjs from the Odyssey SVG set.\n` +
  `// Do not edit by hand — re-run the generator instead.\n` +
  `export const ${name}: Record<string, { viewBox: string; body: string }> = `;

writeFileSync(join(OUT_DIR, 'icons-data.ts'), `${header('THEMEABLE_ICONS')}${JSON.stringify(themeable, null, 2)};\n`);
writeFileSync(join(OUT_DIR, 'brand-icons-data.ts'), `${header('BRAND_ICONS')}${JSON.stringify(brand, null, 2)};\n`);

console.log(`themeable: ${Object.keys(themeable).length}  brand: ${Object.keys(brand).length}  (source: ${SRC})`);
